version: '1'

services:
  cassandra:
    image: cassandra:latest
    ports:
      - '7000:7000'
      - '9042:9042'
    volumes:
      - /lunaria/cassandra/data:/var/lib/cassandra/data
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
