version: '1'

services:
  cassandra:
    container_name: cassandra_auth
    image: cassandra:latest
    ports:
      - '7000:7000'
      - '9042:9042'
    volumes:
      - cassandra_data:/var/lib/cassandra/data
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra

volumes:
  cassandra_data:
    driver: local
